### ISSUE TITLE
User script is disabled by moving to the page such as search, user, and so on.

### ISSUE THREAD

**Issue by mosaicer** [mosaicer/Muting_on_Twitter#4]
By moving to the page, contents of page and url are changed. But user scripts are not reloaded, so you need to reload the page to enable them. I have noticed the problem, but I couldn't solve the problem because of shortage of the knowledge about JavaScript and Twitter Web Client.
Now, I could find the cause! By the next version 6.2, this bug will be fixed :)

**Comment by Croydon** [comment]
Great! After all, this bug was the reason why I stopped using the script :)

**Comment by mosaicer** [comment]
I solved this problem and wrote [the article](http://cyanoa.blogspot.jp/2016/01/web.html) about it __in Japanese__. But, in rare case, user script is still disabled. I'll close this issue if I can solve this problem __completely__.

**Comment by mosaicer** [comment]
I solved this problem completely! I close this issue, but when you face this problem again, please feel free to comment it.
